apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - ingress.yaml
  - sealed-secrets.yaml

images:
  - name: user-service
    newTag: latest
  - name: auth-service
    newTag: latest
  - name: api-gateway
    newTag: latest
  - name: frontend
    newTag: latest


#images:
#  - name: ghcr.io/devopsoct2025team1/devops_oct2025_t01_team1_assignment/user-service
#    newTag: staging
#  - name: ghcr.io/devopsoct2025team1/devops_oct2025_t01_team1_assignment/auth-service
#    newTag: staging
#  - name: ghcr.io/devopsoct2025team1/devops_oct2025_t01_team1_assignment/api-gateway
#    newTag: staging
#  - name: ghcr.io/devopsoct2025team1/devops_oct2025_t01_team1_assignment/frontend
#    newTag: staging

labels:
  - includeSelectors: true
    pairs:
      environment: staging
